name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Using Java 21

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle versionCatalogUpdate
        run: ./gradlew versionCatalogUpdate

      - name: Run Gradle versionCatalogApplyUpdates
        run: ./gradlew versionCatalogApplyUpdates

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update dependencies via versionCatalogUpdate"
            git push
          else
            echo "No changes to commit"
          fi
